# Build by running "snapcraft".

# WARNING:
# Snapcraft uses caching for already build steps but it's buggy and can cause strange problems.
# Clean the cache by running "snapcraft clean".

name: djpdf
license: GPL-3.0+
grade: stable
adopt-info: djpdfgui

base: core22
confinement: strict

architectures:
  - build-on: amd64

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages

apps:
  djpdf:
    command: usr/bin/scans2pdf-gui
    extensions:
      # HINT: Adds plugs and changes environment variables when building and running
      - kde-neon
    common-id: com.github.unrud.djpdf
    desktop: usr/share/applications/com.github.unrud.djpdf.desktop

parts:
  jbig2enc:
    plugin: autotools
    source: https://github.com/agl/jbig2enc/archive/refs/tags/0.29.tar.gz
    source-type: tar
    source-checksum: sha256/bfcf0d0448ee36046af6c776c7271cd5a644855723f0a832d1c0db4de3c21280
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
    build-packages:
      - g++
      - libleptonica-dev
      - zlib1g-dev
    stage-packages:
      - liblept5
      - zlib1g
    override-build: |
      ./autogen.sh
      craftctl default

  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.1-41.tar.gz
    source-type: tar
    source-checksum: sha256/cabf2516dce66da56dd4e3071453b808eefaf4326a93292d2a222a4ea623d601
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
    build-packages:
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libwebp-dev
      - libopenjp2-7-dev
    stage-packages:
      - libjpeg8
      - libpng16-16
      - libtiff5
      - libwebpmux3
      - libgomp1
      - libwebpdemux2
      - libopenjp2-7

  tesseract:
    plugin: autotools
    source: https://github.com/tesseract-ocr/tesseract/archive/refs/tags/5.5.0.tar.gz
    source-checksum: sha256/f2fb34ca035b6d087a42875a35a7a5c4155fa9979c6132365b1e5a28ebc3fc11
    autotools-configure-parameters:
      # WORKAROUND: Fake installation location to find dependencies at runtime
      - --prefix=/snap/djpdf/current/usr
    build-packages:
      - pkg-config
      - libleptonica-dev
      - libcurl4-openssl-dev
    stage-packages:
      - liblept5
      - libcurl4
    override-build: |
      ./autogen.sh
      craftctl default
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/djpdf/current/usr: usr

  tessdata:
    plugin: nil
    build-packages: [wget]
    override-pull: |
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/eng.traineddata -O eng.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/chi_sim.traineddata -O chi_sim.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/hin.traineddata -O hin.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/spa.traineddata -O spa.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/fra.traineddata -O fra.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/ara.traineddata -O ara.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/rus.traineddata -O rus.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/por.traineddata -O por.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/deu.traineddata -O deu.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/jpn.traineddata -O jpn.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.1.0/osd.traineddata -O osd.traineddata
      echo 'daa0c97d651c19fba3b25e81317cd697e9908c8208090c94c3905381c23fc047 *eng.traineddata
      fc05d89ab31d8b4e226910f16a8bcbf78e43bae3e2580bb5feefd052efdab363 *chi_sim.traineddata
      cc76d09fa4fed1c7a4674046e25e63760d0c9bfdce390a52113462c34a556ee6 *hin.traineddata
      0b0fcbb4665189e01ab8019e591f014dd7260460de072543edd4b2cb4ede7c96 *spa.traineddata
      eac01c1d72540d6090facb7b2f42dd0a2ee8fc57c5be1b20548ae668e2761913 *fra.traineddata
      2005976778bbc14fc56a4ea8d43c6080847aeee72fcc2201488f240daca15c5b *ara.traineddata
      681be2c2bead1bc7bd235df88c44e8e60ae73ae866840c0ad4e3b4c247bd37c2 *rus.traineddata
      016c6a371bb1e4c48fe521908cf3ba3d751fade0ab846ad5d4086b563f5c528c *por.traineddata
      896b3b4956503ab9daa10285db330881b2d74b70d889b79262cc534b9ec699a4 *deu.traineddata
      6f416b902d129d8cc28e99c33244034b1cf52549e8560f6320b06d317852159a *jpn.traineddata
      e19f2ae860792fdf372cf48d8ce70ae5da3c4052962fe22e9de1f680c374bb0e *osd.traineddata' > SHA256SUMS
      sha256sum -c SHA256SUMS
    override-build: |
      install -Dm0644 -t "${CRAFT_PART_INSTALL}/usr/share/tessdata" *

  djpdf:
    plugin: python
    source: .
    source-type: git
    python-packages:
      # Dependencies for djpdfgui
      - PySide6<6.8
    stage-packages:
      - python3-pkg-resources
      - qpdf
      - libexempi8
    override-build: |
      craftctl default
      # WORKAROUND: Hardcode libexempi path
      libexempi_path="/snap/djpdf/current/$(realpath --relative-base="${CRAFT_PART_INSTALL}" "$(find "${CRAFT_PART_INSTALL}" -name 'libexempi.so*' -print -quit)")"
      sed -e "s|[^=]*find_library('exempi')| '$libexempi_path'|" -i "${CRAFT_PART_INSTALL}"/lib/python3.*/site-packages/libxmp/exempi.py
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -pyvenv.cfg

  meson-deps:
    # Copied from gnome-42-2204-sdk
    plugin: nil
    source: https://github.com/mesonbuild/meson.git
    source-tag: '1.2.3'
    source-depth: 1
    override-build: |
      python3 -m pip install .
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/meson*
      python3 -m pip install --target=$CRAFT_PART_INSTALL/usr .
      mv $CRAFT_PART_INSTALL/usr/meson* $CRAFT_PART_INSTALL/usr/lib/python3/dist-packages/
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" /usr/local/bin/meson
      sed -i "s%^#!/usr/bin/python3$%#!/usr/bin/env python3%g" $CRAFT_PART_INSTALL/usr/bin/meson
    build-packages:
      - python3-pip
    prime: []

  djpdfgui:
    # WORKAROUND: meson in repository too old
    after: [ meson-deps ]
    plugin: meson
    source: .
    source-type: git
    # WORKAROUND: Fake installation location to find dependencies at runtime
    meson-parameters: [--prefix=/snap/djpdf/current/usr]
    build-packages:
      - ninja-build
      - gettext
      - appstream
      - graphicsmagick-imagemagick-compat
    stage-packages:
      # WORKAROUND: Dependencies required for Qt
      - libxcb-cursor0
    override-pull: |
      craftctl default
      # WORKAROUND: Point icon directly to PNG otherwise snapcraft can't find it
      sed -e 's|Icon=com.github.unrud.djpdf|Icon=/usr/share/icons/hicolor/512x512/apps/com.github.unrud.djpdf.png|' -i desktop/com.github.unrud.djpdf.desktop.in
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${CRAFT_PART_INSTALL}/snap/djpdf/current/usr/bin/scans2pdf-gui"
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/djpdf/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.unrud.djpdf.metainfo.xml]
