# Build by running "snapcraft".

# WARNING:
# Snapcraft uses caching for already build steps but it's buggy and can cause strange problems.
# Clean the cache by running "snapcraft clean".

name: djpdf
license: GPL-3.0+
grade: stable
adopt-info: djpdf

base: core18
confinement: strict

architectures:
  - build-on: amd64

environment:
  TESSDATA_PREFIX: ${SNAP}/share/tessdata
  DJPDF_PLATFORM: xdg-desktop-portal

apps:
  djpdf:
    command: desktop-launch "${SNAP}/bin/scans2pdf-gui"
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
    common-id: com.github.unrud.djpdf
    desktop: usr/share/applications/com.github.unrud.djpdf.desktop
  scans2pdf:
    command: bin/scans2pdf
    plugs:
      - home
  scans2pdf-json:
    command: bin/scans2pdf-json
    plugs:
      - home
  djpdf-json:
    command: bin/djpdf-json
    plugs:
      - home
  hocr-json:
    command: bin/hocr-json

parts:
  jbig2enc:
    plugin: autotools
    source: https://github.com/agl/jbig2enc/archive/0.29.tar.gz
    source-type: tar
    source-checksum: sha256/bfcf0d0448ee36046af6c776c7271cd5a644855723f0a832d1c0db4de3c21280
    build-packages:
      - g++
      - libleptonica-dev
      - zlib1g-dev
    stage-packages:
      - liblept5
      - zlib1g

  openjpeg:
    plugin: cmake
    source: https://github.com/uclouvain/openjpeg/archive/v2.4.0.tar.gz
    source-type: tar
    source-checksum: sha256/8702ba68b442657f11aaeb2b338443ca8d5fb95b0d845757968a7be31ef7f16d

  imagemagick:
    plugin: autotools
    source: https://github.com/ImageMagick/ImageMagick/archive/7.1.0-16.tar.gz
    source-type: tar
    source-checksum: sha256/6eec33290655c403af7ed41569e1c9a9d1c29f41df51b1a83207e5da8ef90b61
    after: [openjpeg]
    build-packages:
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libwebp-dev
    stage-packages:
      - libjpeg8
      - libpng16-16
      - libtiff5
      - libwebpmux3
      - libgomp1
      - libwebpdemux2

  tesseract:
    plugin: autotools
    source: https://github.com/tesseract-ocr/tesseract/archive/5.0.0.tar.gz
    source-checksum: sha256/72467b7876dc0c39ef7fbcb0f793f73aee1c78d9fabab3ab19cbac1eb42e9fed
    build-packages:
      - pkg-config
      - libleptonica-dev
    stage-packages:
      - liblept5

  tessdata:
    plugin: nil
    build-packages: [wget]
    override-pull: |
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/eng.traineddata -O eng.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/chi_sim.traineddata -O chi_sim.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/hin.traineddata -O hin.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/spa.traineddata -O spa.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/fra.traineddata -O fra.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/ara.traineddata -O ara.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/rus.traineddata -O rus.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/por.traineddata -O por.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/deu.traineddata -O deu.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/jpn.traineddata -O jpn.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/osd.traineddata -O osd.traineddata
      wget https://github.com/tesseract-ocr/tessdata/raw/4.0.0/equ.traineddata -O equ.traineddata
      echo 'daa0c97d651c19fba3b25e81317cd697e9908c8208090c94c3905381c23fc047 *eng.traineddata
      fc05d89ab31d8b4e226910f16a8bcbf78e43bae3e2580bb5feefd052efdab363 *chi_sim.traineddata
      cc76d09fa4fed1c7a4674046e25e63760d0c9bfdce390a52113462c34a556ee6 *hin.traineddata
      0b0fcbb4665189e01ab8019e591f014dd7260460de072543edd4b2cb4ede7c96 *spa.traineddata
      eac01c1d72540d6090facb7b2f42dd0a2ee8fc57c5be1b20548ae668e2761913 *fra.traineddata
      2005976778bbc14fc56a4ea8d43c6080847aeee72fcc2201488f240daca15c5b *ara.traineddata
      681be2c2bead1bc7bd235df88c44e8e60ae73ae866840c0ad4e3b4c247bd37c2 *rus.traineddata
      016c6a371bb1e4c48fe521908cf3ba3d751fade0ab846ad5d4086b563f5c528c *por.traineddata
      896b3b4956503ab9daa10285db330881b2d74b70d889b79262cc534b9ec699a4 *deu.traineddata
      6f416b902d129d8cc28e99c33244034b1cf52549e8560f6320b06d317852159a *jpn.traineddata
      e19f2ae860792fdf372cf48d8ce70ae5da3c4052962fe22e9de1f680c374bb0e *osd.traineddata
      8f660323d8a7b7a0e8d2fae1a3439e6e470222bfbb990b2ab7fe9e1fb4791c0b *equ.traineddata' > SHA256SUMS
      sha256sum -c SHA256SUMS
    override-build: |
      install -Dm0644 -t "${SNAPCRAFT_PART_INSTALL}/share/tessdata" *

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  djpdf:
    after:
      - desktop-glib-only
    plugin: python
    python-version: python3
    source: .
    source-type: git
    python-packages:
      - PySide2<5.15
    build-packages:
      - imagemagick
    stage-packages:
      - python3-pkg-resources
      - python3-dbus
      - qpdf
      - libexempi3
      - libnss3
      - libxcomposite1
      - libxcursor1
      - libxtst6
      - libxrandr2
      - libasound2
      - libglu1-mesa
      - libgles2-mesa
      - fontconfig
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgdk-pixbuf2.0-0
      - locales-all
      - libxslt1.1
      - fonts-dejavu-core
      - xfonts-base
      - xfonts-scalable
      - libxkbcommon-x11-0
    override-pull: |
      snapcraftctl pull
      # WORKAROUND: Point icon directly to high resolution version otherwise snapcraft automatically chooses lowest resolution
      sed -e 's|Icon=com.github.unrud.djpdf|Icon=/usr/share/icons/hicolor/512x512/apps/com.github.unrud.djpdf.png|' -i desktop/com.github.unrud.djpdf.desktop
    override-build: |
      snapcraftctl build
      install -Dm0644 -t "${SNAPCRAFT_PART_INSTALL}/usr/share/metainfo" desktop/com.github.unrud.djpdf.metainfo.xml
      install -Dm0644 -t "${SNAPCRAFT_PART_INSTALL}/usr/share/applications" desktop/com.github.unrud.djpdf.desktop
      for s in 16 32 48 64 128 256 512; do
        convert +set date:create +set date:modify desktop/com.github.unrud.djpdf.png -resize ${s}x${s} com.github.unrud.djpdf_${s}.png || exit 1
        install -Dm0644 com.github.unrud.djpdf_${s}.png "${SNAPCRAFT_PART_INSTALL}/usr/share/icons/hicolor/${s}x${s}/apps/com.github.unrud.djpdf.png" || exit 1
      done
    override-stage: |
      # WORKAROUND: Hardcode libexempi path
      libexempi_path="/snap/djpdf/current/$(realpath --relative-base="${SNAPCRAFT_PART_INSTALL}" "$(find "${SNAPCRAFT_PART_INSTALL}" -name 'libexempi.so*' -print -quit)")"
      sed -e "s|[^=]*find_library('exempi')| '$libexempi_path'|" -i "${SNAPCRAFT_PART_INSTALL}"/lib/python3.*/site-packages/libxmp/exempi.py
      snapcraftctl stage
    parse-info: [usr/share/metainfo/com.github.unrud.djpdf.metainfo.xml]
